#spring.application.name=sisco-e
#spring.datasource.url=jdbc:postgresql://192.168.1.94:5432/financas?currentSchema=escola
#Força o Spring a carregar o arquivo .env se ele existir na raiz
spring.config.import=optional:file:.env[.properties]

#server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#Sobre o docker ao iniciar a aplicacao e desce ao parar - docker compose up/down
spring.docker.compose.enabled=false

#JWT
spring.app.jwtSecretKey=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION}

#valor padrão de 86400000 (24 horas) para o ambiente de desenvolvimento local, caso a variável não esteja definida no sistema
#spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS:86400000}

#Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/financas
#spring.datasource.username=cleber
#spring.datasource.password=QssyaG!hk5ag
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.jpa.show-sql=true



