CREATE TABLE IF NOT EXISTS siscoescola.revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS siscoescola.tb_escola_aud (
    id_escola UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    nome_escola CHARACTER VARYING(120),
    codigo_escola CHARACTER VARYING(120),
    municipio CHARACTER VARYING(120),
    estado CHARACTER VARYING(2),
    cep CHARACTER VARYING(8),
    logradouro CHARACTER VARYING(255),
    bairro CHARACTER VARYING(255),
    tipo_escola CHARACTER VARYING(30),
    is_ativo BOOLEAN,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    CONSTRAINT pk_tb_escola_aud PRIMARY KEY (id_escola, rev),
    CONSTRAINT fk_tb_escola_aud_revinfo FOREIGN KEY (rev)
        REFERENCES siscoescola.revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_tb_escola_aud_rev ON siscoescola.tb_escola_aud (rev);

CREATE TABLE IF NOT EXISTS siscoescola.tb_usuario_aud (
    id_usuario UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    nome_completo CHARACTER VARYING(120),
    username CHARACTER VARYING(120),
    cpf CHARACTER VARYING(11),
    email CHARACTER VARYING(120),
    password CHARACTER VARYING(255),
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    is_ativo BOOLEAN,
    CONSTRAINT pk_tb_usuario_aud PRIMARY KEY (id_usuario, rev),
    CONSTRAINT fk_tb_usuario_aud_revinfo FOREIGN KEY (rev)
        REFERENCES siscoescola.revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_tb_usuario_aud_rev ON siscoescola.tb_usuario_aud (rev);

CREATE TABLE IF NOT EXISTS siscoescola.tb_diretor_aud (
    id_diretor UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    nome_diretor CHARACTER VARYING(120),
    cpf CHARACTER VARYING(11),
    email CHARACTER VARYING(120),
    is_ativo BOOLEAN,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    id_escola UUID,
    CONSTRAINT pk_tb_diretor_aud PRIMARY KEY (id_diretor, rev),
    CONSTRAINT fk_tb_diretor_aud_revinfo FOREIGN KEY (rev)
        REFERENCES siscoescola.revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_tb_diretor_aud_rev ON siscoescola.tb_diretor_aud (rev);
